name: Action1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step2.1
        run: echo "teste 2.1"
      - name: Step2.2
        run: echo "teste 2.2"