name: Action-Testes
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: jabbukka/jenkins-trigger@main
        with:
          url: "https://esteira.dev.processoeletronico.gov.br"
          job_name: "PEN/job/jobtmp2"
          user_name: "jenkinsadmin"
          api_token: "1118a53cb255fda235c51c37dae46041eb"
          wait: "true"
